# Generated by Django 4.1.7 on 2023-02-25 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('resource_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('resource_name', models.CharField(max_length=100)),
                ('resource_url', models.CharField(max_length=255)),
                ('top_tag', models.CharField(max_length=255)),
                ('bottom_tag', models.CharField(max_length=255)),
                ('title_cut', models.CharField(max_length=255)),
                ('date_cut', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('link', models.CharField(max_length=255)),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('nd_date', models.CharField(max_length=100)),
                ('s_date', models.DateTimeField(auto_now_add=True)),
                ('not_date', models.CharField(max_length=100)),
                ('res_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.resource')),
            ],
        ),
    ]
